#Batter Points

SELECT '###################################' AS '';
SELECT '# DATA PROCESSING SCRIPT STARTED  #' AS '';
SELECT '###################################' AS '';
SELECT NOW() AS 'Script Start Time';
SELECT 'Expected total runtime: 30-55 minutes' AS '';
SELECT '' AS '';

SET @single = 3;
SET @double=5;
SET @triple=8;
SET @hr=10   ;
SET @rbi=2   ;
SET @run=2   ;
SET @walk=2  ;
SET @hbp=2   ;
SET @sb=5    ;

#Pitcher Points
SET @ip=2.25; #innings pitched
SET @so=2; #strikeout
SET @win=4;
SET @era=-2; #earned run allowed
SET @ha=-0.6; #hit against (allowed a hit)
SET @walk=-0.6;
SET @hb=-0.6; #hit batter
SET @cg=2.5; #complete game
SET @cgs=2.5; #complete game shutout
SET @nh=5; #no hitter

SELECT '========================================' AS '';
SELECT 'Starting at_bat_level table creation' AS '';
SELECT NOW() AS 'Start Time';
SELECT '========================================' AS '';

DROP TABLE IF EXISTS retrosheet.at_bat_level;
CREATE TABLE retrosheet.at_bat_level (
	seq_events INT,
	YEAR_ID INT,
	GAME_ID VARCHAR(12),
	GAME_DATE DATE,
	bat_id VARCHAR(8),
	PA_BALL_CT INT,
	PA_SWINGMISS_STRIKE_CT INT,
	BAT_HOME_ID INT,
	BAT_FATE_ID INT,
	EVENT_CD INT,
	RBI_CT INT,
	event_tx VARCHAR(100),
	BAT_LINEUP_ID INT,
	BASE1_RUN_ID VARCHAR(8),
	BASE2_RUN_ID VARCHAR(8),
	BASE3_RUN_ID VARCHAR(8),
	RUN1_SB_FL CHAR(1),
	RUN2_SB_FL CHAR(1),
	RUN3_SB_FL CHAR(1),
	ab_fl CHAR(1),
	PR_Run1_fl CHAR(1),
	PR_Run2_fl CHAR(1),
	PR_Run3_fl CHAR(1),
	INN_CT INT,
	AWAY_SCORE_CT INT,
	HOME_SCORE_CT INT,
	HOME_TEAM_ID VARCHAR(3),
	BAT_HAND_CD CHAR(1),
	PIT_HAND_CD CHAR(1),
	PIT_ID VARCHAR(8),
	TEMP_PARK_CT INT,
	WIND_DIRECTION_PARK_CD VARCHAR(20),
	WIND_SPEED_PARK_CT INT,
	PRECIP_PARK_CD VARCHAR(20),
	SKY_PARK_CD VARCHAR(20),
	WIN_PIT_ID VARCHAR(8),
	park_id VARCHAR(5),
	DAYNIGHT_PARK_CD CHAR(1),
	game_hits INT,
	game_ab INT,
	game_ba DECIMAL(5,4),
	game_singles INT,
	game_doubles INT,
	game_triples INT,
	game_hr INT,
	game_pa INT,
	game_ibb INT,
	game_ubb INT,
	game_balls INT,
	game_swing_strikes INT,
	season_hits INT,
	season_ab INT,
	season_ba DECIMAL(5,4),
	season_singles INT,
	season_doubles INT,
	season_triples INT,
	season_hr INT,
	season_pa INT,
	season_ibb INT,
	season_ubb INT,
	season_balls INT,
	season_swing_strikes INT,
	hit_fl INT,
	pitching_points DECIMAL(5,2),
	batting_points DECIMAL(5,2),
	MATCHUP_IN INT,
	PRIMARY KEY (YEAR_ID, GAME_ID, seq_events),
	INDEX idx_bat_date (bat_id, GAME_DATE, YEAR_ID),
	INDEX idx_game_bat (GAME_ID, bat_id),
	INDEX idx_year_date (YEAR_ID, GAME_DATE)
)
PARTITION BY RANGE (YEAR_ID) (
	PARTITION p1952 VALUES LESS THAN (1953),
	PARTITION p1953 VALUES LESS THAN (1954),
	PARTITION p1954 VALUES LESS THAN (1955),
	PARTITION p1955 VALUES LESS THAN (1956),
	PARTITION p1956 VALUES LESS THAN (1957),
	PARTITION p1957 VALUES LESS THAN (1958),
	PARTITION p1958 VALUES LESS THAN (1959),
	PARTITION p1959 VALUES LESS THAN (1960),
	PARTITION p1960 VALUES LESS THAN (1961),
	PARTITION p1961 VALUES LESS THAN (1962),
	PARTITION p1962 VALUES LESS THAN (1963),
	PARTITION p1963 VALUES LESS THAN (1964),
	PARTITION p1964 VALUES LESS THAN (1965),
	PARTITION p1965 VALUES LESS THAN (1966),
	PARTITION p1966 VALUES LESS THAN (1967),
	PARTITION p1967 VALUES LESS THAN (1968),
	PARTITION p1968 VALUES LESS THAN (1969),
	PARTITION p1969 VALUES LESS THAN (1970),
	PARTITION p1970 VALUES LESS THAN (1971),
	PARTITION p1971 VALUES LESS THAN (1972),
	PARTITION p1972 VALUES LESS THAN (1973),
	PARTITION p1973 VALUES LESS THAN (1974),
	PARTITION p1974 VALUES LESS THAN (1975),
	PARTITION p1975 VALUES LESS THAN (1976),
	PARTITION p1976 VALUES LESS THAN (1977),
	PARTITION p1977 VALUES LESS THAN (1978),
	PARTITION p1978 VALUES LESS THAN (1979),
	PARTITION p1979 VALUES LESS THAN (1980),
	PARTITION p1980 VALUES LESS THAN (1981),
	PARTITION p1981 VALUES LESS THAN (1982),
	PARTITION p1982 VALUES LESS THAN (1983),
	PARTITION p1983 VALUES LESS THAN (1984),
	PARTITION p1984 VALUES LESS THAN (1985),
	PARTITION p1985 VALUES LESS THAN (1986),
	PARTITION p1986 VALUES LESS THAN (1987),
	PARTITION p1987 VALUES LESS THAN (1988),
	PARTITION p1988 VALUES LESS THAN (1989),
	PARTITION p1989 VALUES LESS THAN (1990),
	PARTITION p1990 VALUES LESS THAN (1991),
	PARTITION p1991 VALUES LESS THAN (1992),
	PARTITION p1992 VALUES LESS THAN (1993),
	PARTITION p1993 VALUES LESS THAN (1994),
	PARTITION p1994 VALUES LESS THAN (1995),
	PARTITION p1995 VALUES LESS THAN (1996),
	PARTITION p1996 VALUES LESS THAN (1997),
	PARTITION p1997 VALUES LESS THAN (1998),
	PARTITION p1998 VALUES LESS THAN (1999),
	PARTITION p1999 VALUES LESS THAN (2000),
	PARTITION p2000 VALUES LESS THAN (2001),
	PARTITION p2001 VALUES LESS THAN (2002),
	PARTITION p2002 VALUES LESS THAN (2003),
	PARTITION p2003 VALUES LESS THAN (2004),
	PARTITION p2004 VALUES LESS THAN (2005),
	PARTITION p2005 VALUES LESS THAN (2006),
	PARTITION p2006 VALUES LESS THAN (2007),
	PARTITION p2007 VALUES LESS THAN (2008),
	PARTITION p2008 VALUES LESS THAN (2009),
	PARTITION p2009 VALUES LESS THAN (2010),
	PARTITION p2010 VALUES LESS THAN (2011),
	PARTITION p2011 VALUES LESS THAN (2012),
	PARTITION p2012 VALUES LESS THAN (2013),
	PARTITION p2013 VALUES LESS THAN (2014),
	PARTITION p2014 VALUES LESS THAN (2015),
	PARTITION p2015 VALUES LESS THAN (2016),
	PARTITION p2016 VALUES LESS THAN (2017),
	PARTITION p2017 VALUES LESS THAN (2018),
	PARTITION p2018 VALUES LESS THAN (2019),
	PARTITION p2019 VALUES LESS THAN (2020),
	PARTITION p2020 VALUES LESS THAN (2021),
	PARTITION p2021 VALUES LESS THAN (2022),
	PARTITION p2022 VALUES LESS THAN (2023),
	PARTITION p2023 VALUES LESS THAN (2024),
	PARTITION p2024 VALUES LESS THAN (2025),
	PARTITION p2025 VALUES LESS THAN (2026),
	PARTITION p_future VALUES LESS THAN MAXVALUE
);

SELECT 'at_bat_level table structure created' AS '';
SELECT NOW() AS 'Time';
SELECT 'Starting INSERT into at_bat_level (this will take 25-45 minutes)...' AS '';

INSERT INTO retrosheet.at_bat_level
	SELECT seq_events,
	       E.YEAR_ID,
	       E.GAME_ID,
	       STR_TO_DATE(SUBSTRING(E.GAME_ID, 4, 8), '%Y%m%d') AS GAME_DATE,
	       bat_id,
	       PA_BALL_CT,
	       PA_SWINGMISS_STRIKE_CT,
	       BAT_HOME_ID,
	       BAT_FATE_ID,
	       EVENT_CD,
	       RBI_CT,
	       event_tx,
	       BAT_LINEUP_ID,
	       BASE1_RUN_ID,
	       BASE2_RUN_ID,
	       BASE3_RUN_ID,
	       RUN1_SB_FL,
	       RUN2_SB_FL,
	       RUN3_SB_FL,
	       ab_fl,
	       PR_Run1_fl,
	       PR_Run2_fl,
	       PR_Run3_fl,
	       INN_CT,
	       AWAY_SCORE_CT,
	       HOME_SCORE_CT,
	       HOME_TEAM_ID,
	       BAT_HAND_CD,
	       PIT_HAND_CD,
	       PIT_ID,
	       TEMP_PARK_CT,
	       WIND_DIRECTION_PARK_CD,
	       WIND_SPEED_PARK_CT,
	       PRECIP_PARK_CD,
	       SKY_PARK_CD,
	       WIN_PIT_ID,
	       park_id,
	       DAYNIGHT_PARK_CD,
		SUM(CASE WHEN EVENT_CD IN ("20", "21", "22", "23") THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, GAME_ID ORDER BY E.GAME_ID, bat_id, INN_CT) AS game_hits,
		SUM(CASE WHEN ab_fl= 'T' THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, GAME_ID ORDER BY E.GAME_ID, bat_id, INN_CT) AS game_ab,
		SUM(CASE WHEN EVENT_CD IN ("20", "21", "22", "23") THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, GAME_ID ORDER BY E.GAME_ID, bat_id, INN_CT)/NULLIF(SUM(CASE WHEN ab_fl= 'T' THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, GAME_ID ORDER BY bat_id, E.GAME_ID, INN_CT), 0) AS game_ba,
		SUM(CASE WHEN EVENT_CD = '20' THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, GAME_ID ORDER BY E.GAME_ID, bat_id, INN_CT) AS game_singles,
		SUM(CASE WHEN EVENT_CD = '21' THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, GAME_ID ORDER BY E.GAME_ID, bat_id, INN_CT) AS game_doubles,
		SUM(CASE WHEN EVENT_CD = '22' THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, GAME_ID ORDER BY E.GAME_ID, bat_id, INN_CT) AS game_triples,
		SUM(CASE WHEN EVENT_CD = '23' THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, GAME_ID ORDER BY E.GAME_ID, bat_id, INN_CT) AS game_hr,
		SUM(CASE WHEN ab_fl = 'T' OR EVENT_CD IN (14, 15, 16) THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, GAME_ID ORDER BY E.GAME_ID, bat_id, INN_CT) AS game_pa,
		SUM(CASE WHEN EVENT_CD = '15' THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, GAME_ID ORDER BY E.GAME_ID, bat_id, INN_CT) AS game_ibb,
		SUM(CASE WHEN EVENT_CD = '14' THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, GAME_ID ORDER BY E.GAME_ID, bat_id, INN_CT) AS game_ubb,
		SUM(PA_BALL_CT) OVER (PARTITION BY bat_id, GAME_ID ORDER BY E.GAME_ID, bat_id, INN_CT) AS game_balls,
		SUM(PA_SWINGMISS_STRIKE_CT) OVER (PARTITION BY bat_id, GAME_ID ORDER BY E.GAME_ID, bat_id, INN_CT) AS game_swing_strikes,
		SUM(CASE WHEN EVENT_CD IN ("20", "21", "22", "23") THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, E.YEAR_ID ORDER BY E.GAME_ID, INN_CT) AS season_hits,
		SUM(CASE WHEN ab_fl= 'T' THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, E.YEAR_ID ORDER BY E.GAME_ID, INN_CT) AS season_ab,
		SUM(CASE WHEN EVENT_CD IN ("20", "21", "22", "23") THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, E.YEAR_ID ORDER BY E.GAME_ID, INN_CT)/NULLIF(SUM(CASE WHEN ab_fl= 'T' THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, E.YEAR_ID ORDER BY E.GAME_ID, INN_CT), 0) AS season_ba,
		SUM(CASE WHEN EVENT_CD = '20' THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, E.YEAR_ID ORDER BY E.GAME_ID, INN_CT) AS season_singles,
		SUM(CASE WHEN EVENT_CD = '21' THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, E.YEAR_ID ORDER BY E.GAME_ID, INN_CT) AS season_doubles,
		SUM(CASE WHEN EVENT_CD = '22' THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, E.YEAR_ID ORDER BY E.GAME_ID, INN_CT) AS season_triples,
		SUM(CASE WHEN EVENT_CD = '23' THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, E.YEAR_ID ORDER BY E.GAME_ID, INN_CT) AS season_hr,
		SUM(CASE WHEN ab_fl = 'T' OR EVENT_CD IN (14, 15, 16) THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, E.YEAR_ID ORDER BY E.GAME_ID, INN_CT) AS season_pa,
		SUM(CASE WHEN EVENT_CD = '15' THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, E.YEAR_ID ORDER BY E.GAME_ID, INN_CT) AS season_ibb,
		SUM(CASE WHEN EVENT_CD = '14' THEN 1 ELSE 0 END) OVER (PARTITION BY bat_id, E.YEAR_ID ORDER BY E.GAME_ID, INN_CT) AS season_ubb,
		SUM(PA_BALL_CT) OVER (PARTITION BY bat_id, E.YEAR_ID ORDER BY E.GAME_ID, INN_CT) AS season_balls,
		SUM(PA_SWINGMISS_STRIKE_CT) OVER (PARTITION BY bat_id, E.YEAR_ID ORDER BY E.GAME_ID, INN_CT) AS season_swing_strikes,


	       -- Add the case expression for hit_fl
	       CASE WHEN EVENT_CD IN ("20", "21", "22", "23") THEN 1 ELSE 0 END AS hit_fl,
	       -- Add the case expression for pitchingpoints
	       CASE
		 WHEN EVENT_CD = "3" THEN 2
		 WHEN EVENT_CD IN ("20", "21", "22", "23") THEN -0.6 #hit_fl logic
		 WHEN EVENT_CD IN ("14", "16") THEN -0.6
		 ELSE 0
	       END AS pitching_points,
	       -- Add the case expression for fantasypoints
		      CASE
		 WHEN EVENT_CD = "23" THEN @hr
		 WHEN EVENT_CD = "20" THEN @single + RBI_CT * @rbi
		 WHEN EVENT_CD = "21" THEN @double + RBI_CT * @rbi
		 WHEN EVENT_CD IN ("14", "16") THEN @walk + RBI_CT * @rbi
		 WHEN EVENT_CD = "22" THEN @triple + RBI_CT * @rbi
		 ELSE 0
	       END AS batting_points,
	       CASE
		 WHEN BAT_HAND_CD = 'R' AND PIT_HAND_CD = 'R' THEN 1
		 WHEN BAT_HAND_CD = 'R' AND PIT_HAND_CD = 'L' THEN 2
		 WHEN BAT_HAND_CD = 'L' AND PIT_HAND_CD = 'R' THEN 3
		 ELSE 4
	       END AS MATCHUP_IN

	FROM retrosheet.events E
	LEFT JOIN (
	  SELECT year_id,
		 GAME_ID,
		 TEMP_PARK_CT,
		 WIND_DIRECTION_PARK_CD,
		 WIND_SPEED_PARK_CT,
		 PRECIP_PARK_CD,
		 SKY_PARK_CD,
		 WIN_PIT_ID,
		 park_id,
		 DAYNIGHT_PARK_CD
	  FROM retrosheet.games
	) G
	ON E.GAME_ID = G.GAME_ID
;

SELECT '========================================' AS '';
SELECT 'at_bat_level INSERT completed' AS '';
SELECT NOW() AS 'Completion Time';
SELECT CONCAT('Rows inserted: ', COUNT(*)) AS 'Row Count' FROM retrosheet.at_bat_level;
SELECT '========================================' AS '';

SELECT '========================================' AS '';
SELECT 'Starting game_matchup_level table creation' AS '';
SELECT NOW() AS 'Start Time';
SELECT '========================================' AS '';

DROP TABLE IF EXISTS retrosheet.game_matchup_level;
CREATE TABLE retrosheet.game_matchup_level (
	YEAR_ID INT,
	GAME_ID VARCHAR(12),
	GAME_DATE DATE,
	BAT_HAND_CD CHAR(1),
	PIT_HAND_CD CHAR(1),
	bat_id VARCHAR(8),
	BAT_HOME_ID INT,
	RBI_CT INT,
	BAT_LINEUP_ID INT,
	AWAY_SCORE_CT INT,
	HOME_SCORE_CT INT,
	HOME_TEAM_ID VARCHAR(3),
	TEMP_PARK_CT INT,
	WIND_DIRECTION_PARK_CD VARCHAR(20),
	WIND_SPEED_PARK_CT INT,
	PRECIP_PARK_CD VARCHAR(20),
	SKY_PARK_CD VARCHAR(20),
	WIN_PIT_ID VARCHAR(8),
	park_id VARCHAR(5),
	DAYNIGHT_PARK_CD CHAR(1),
	game_hits INT,
	game_ab INT,
	game_singles INT,
	game_doubles INT,
	game_triples INT,
	game_hr INT,
	game_pa INT,
	game_ibb INT,
	game_ubb INT,
	game_balls INT,
	game_swing_strikes INT,
	pitching_points DECIMAL(5,2),
	batting_points DECIMAL(5,2),
	PRIMARY KEY (YEAR_ID, GAME_ID, bat_id, BAT_HAND_CD, PIT_HAND_CD),
	INDEX idx_bat_date (bat_id, GAME_DATE, YEAR_ID),
	INDEX idx_year_game (YEAR_ID, GAME_ID)
)
PARTITION BY RANGE (YEAR_ID) (
	PARTITION p1952 VALUES LESS THAN (1953),
	PARTITION p1953 VALUES LESS THAN (1954),
	PARTITION p1954 VALUES LESS THAN (1955),
	PARTITION p1955 VALUES LESS THAN (1956),
	PARTITION p1956 VALUES LESS THAN (1957),
	PARTITION p1957 VALUES LESS THAN (1958),
	PARTITION p1958 VALUES LESS THAN (1959),
	PARTITION p1959 VALUES LESS THAN (1960),
	PARTITION p1960 VALUES LESS THAN (1961),
	PARTITION p1961 VALUES LESS THAN (1962),
	PARTITION p1962 VALUES LESS THAN (1963),
	PARTITION p1963 VALUES LESS THAN (1964),
	PARTITION p1964 VALUES LESS THAN (1965),
	PARTITION p1965 VALUES LESS THAN (1966),
	PARTITION p1966 VALUES LESS THAN (1967),
	PARTITION p1967 VALUES LESS THAN (1968),
	PARTITION p1968 VALUES LESS THAN (1969),
	PARTITION p1969 VALUES LESS THAN (1970),
	PARTITION p1970 VALUES LESS THAN (1971),
	PARTITION p1971 VALUES LESS THAN (1972),
	PARTITION p1972 VALUES LESS THAN (1973),
	PARTITION p1973 VALUES LESS THAN (1974),
	PARTITION p1974 VALUES LESS THAN (1975),
	PARTITION p1975 VALUES LESS THAN (1976),
	PARTITION p1976 VALUES LESS THAN (1977),
	PARTITION p1977 VALUES LESS THAN (1978),
	PARTITION p1978 VALUES LESS THAN (1979),
	PARTITION p1979 VALUES LESS THAN (1980),
	PARTITION p1980 VALUES LESS THAN (1981),
	PARTITION p1981 VALUES LESS THAN (1982),
	PARTITION p1982 VALUES LESS THAN (1983),
	PARTITION p1983 VALUES LESS THAN (1984),
	PARTITION p1984 VALUES LESS THAN (1985),
	PARTITION p1985 VALUES LESS THAN (1986),
	PARTITION p1986 VALUES LESS THAN (1987),
	PARTITION p1987 VALUES LESS THAN (1988),
	PARTITION p1988 VALUES LESS THAN (1989),
	PARTITION p1989 VALUES LESS THAN (1990),
	PARTITION p1990 VALUES LESS THAN (1991),
	PARTITION p1991 VALUES LESS THAN (1992),
	PARTITION p1992 VALUES LESS THAN (1993),
	PARTITION p1993 VALUES LESS THAN (1994),
	PARTITION p1994 VALUES LESS THAN (1995),
	PARTITION p1995 VALUES LESS THAN (1996),
	PARTITION p1996 VALUES LESS THAN (1997),
	PARTITION p1997 VALUES LESS THAN (1998),
	PARTITION p1998 VALUES LESS THAN (1999),
	PARTITION p1999 VALUES LESS THAN (2000),
	PARTITION p2000 VALUES LESS THAN (2001),
	PARTITION p2001 VALUES LESS THAN (2002),
	PARTITION p2002 VALUES LESS THAN (2003),
	PARTITION p2003 VALUES LESS THAN (2004),
	PARTITION p2004 VALUES LESS THAN (2005),
	PARTITION p2005 VALUES LESS THAN (2006),
	PARTITION p2006 VALUES LESS THAN (2007),
	PARTITION p2007 VALUES LESS THAN (2008),
	PARTITION p2008 VALUES LESS THAN (2009),
	PARTITION p2009 VALUES LESS THAN (2010),
	PARTITION p2010 VALUES LESS THAN (2011),
	PARTITION p2011 VALUES LESS THAN (2012),
	PARTITION p2012 VALUES LESS THAN (2013),
	PARTITION p2013 VALUES LESS THAN (2014),
	PARTITION p2014 VALUES LESS THAN (2015),
	PARTITION p2015 VALUES LESS THAN (2016),
	PARTITION p2016 VALUES LESS THAN (2017),
	PARTITION p2017 VALUES LESS THAN (2018),
	PARTITION p2018 VALUES LESS THAN (2019),
	PARTITION p2019 VALUES LESS THAN (2020),
	PARTITION p2020 VALUES LESS THAN (2021),
	PARTITION p2021 VALUES LESS THAN (2022),
	PARTITION p2022 VALUES LESS THAN (2023),
	PARTITION p2023 VALUES LESS THAN (2024),
	PARTITION p2024 VALUES LESS THAN (2025),
	PARTITION p2025 VALUES LESS THAN (2026),
	PARTITION p_future VALUES LESS THAN MAXVALUE
);

SELECT 'game_matchup_level table structure created' AS '';
SELECT NOW() AS 'Time';
SELECT 'Starting INSERT into game_matchup_level...' AS '';

INSERT INTO retrosheet.game_matchup_level
SELECT	YEAR_ID,
	       GAME_ID,
	       GAME_DATE,
	       BAT_HAND_CD,
	       PIT_HAND_CD,
	       bat_id,
	       #PIT_ID,
	       MAX(BAT_HOME_ID             ) AS BAT_HOME_ID,
	       SUM(RBI_CT                  ) AS RBI_CT,
	       MAX(BAT_LINEUP_ID           ) AS  BAT_LINEUP_ID,
	       MAX(AWAY_SCORE_CT           ) AS  AWAY_SCORE_CT,
	       MAX(HOME_SCORE_CT           ) AS  HOME_SCORE_CT,
	       MAX(HOME_TEAM_ID  	   ) AS  HOME_TEAM_ID,
	       MAX(TEMP_PARK_CT            ) AS  TEMP_PARK_CT,
	       MAX(WIND_DIRECTION_PARK_CD  ) AS  WIND_DIRECTION_PARK_CD,
	       MAX(WIND_SPEED_PARK_CT      ) AS  WIND_SPEED_PARK_CT,
	       MAX(PRECIP_PARK_CD          ) AS  PRECIP_PARK_CD,
	       MAX(SKY_PARK_CD             ) AS  SKY_PARK_CD,
	       MAX(WIN_PIT_ID              ) AS  WIN_PIT_ID,
	       MAX(park_id                 ) AS  park_id,
	       MAX(DAYNIGHT_PARK_CD	   ) AS  DAYNIGHT_PARK_CD ,
	       MAX( game_hits               ) AS  game_hits         ,
	       MAX( game_ab                 ) AS  game_ab           ,
	       MAX( game_singles            ) AS  game_singles      ,
	       MAX( game_doubles            ) AS  game_doubles      ,
	       MAX( game_triples            ) AS  game_triples      ,
	       MAX( game_hr                 ) AS  game_hr           ,
	       MAX( game_pa                 ) AS  game_pa           ,
	       MAX( game_ibb                ) AS  game_ibb          ,
	       MAX( game_ubb                ) AS  game_ubb          ,
	       MAX( game_balls              ) AS  game_balls        ,
	       MAX( game_swing_strikes       ) AS  game_swing_strikes ,
	       MAX( pitching_points         ) AS  pitching_points   ,
	       MAX( batting_points          ) AS  batting_points

	FROM retrosheet.at_bat_level
	GROUP BY YEAR_ID, GAME_ID, GAME_DATE, BAT_HAND_CD, PIT_HAND_CD, bat_id#, PIT_ID
	;

SELECT '========================================' AS '';
SELECT 'game_matchup_level INSERT completed' AS '';
SELECT NOW() AS 'Completion Time';
SELECT CONCAT('Rows inserted: ', COUNT(*)) AS 'Row Count' FROM retrosheet.game_matchup_level;
SELECT '========================================' AS '';

SELECT '========================================' AS '';
SELECT 'Starting stolen_bases table creation' AS '';
SELECT NOW() AS 'Start Time';
SELECT '========================================' AS '';

DROP TABLE IF EXISTS retrosheet.stolen_bases;
CREATE TABLE retrosheet.stolen_bases (
	GAME_ID VARCHAR(12),
	GAME_DATE DATE,
	BASE_STL_ID VARCHAR(8),
	STOLEN_BASE_FL INT,
	PIT_HAND_CD CHAR(1),
	STOLEN_BASE_POINTS INT,
	PRIMARY KEY (GAME_ID, BASE_STL_ID, STOLEN_BASE_FL, PIT_HAND_CD),
	INDEX idx_player_date (BASE_STL_ID, GAME_DATE),
	INDEX idx_game (GAME_ID)
);

SELECT 'stolen_bases table structure created' AS '';
SELECT NOW() AS 'Time';
SELECT 'Starting INSERT into stolen_bases...' AS '';

INSERT INTO retrosheet.stolen_bases
	SELECT GAME_ID
	      , GAME_DATE
	      , BASE_STL_ID
	      , STOLEN_BASE_FL
	      , PIT_HAND_CD
	      , SUM(STOLEN_BASE_POINTS) AS STOLEN_BASE_POINTS
	FROM (
		SELECT GAME_ID
		, STR_TO_DATE(SUBSTRING(GAME_ID, 4, 8), '%Y%m%d') AS GAME_DATE
		, RUN1_SB_FL
		, RUN2_SB_FL
		, RUN3_SB_FL
		, BASE1_RUN_ID
		, BASE2_RUN_ID
		, BASE3_RUN_ID
		, PIT_HAND_CD
		, event_cd
		, CASE
		  WHEN RUN1_SB_FL = 'T' AND RUN2_SB_FL = 'T' THEN BASE1_RUN_ID
		  WHEN RUN1_SB_FL = 'T' AND RUN3_SB_FL = 'T' THEN BASE1_RUN_ID
		  WHEN RUN2_SB_FL = 'T' AND RUN3_SB_FL = 'T' THEN BASE2_RUN_ID
		  WHEN RUN1_SB_FL = 'T' THEN BASE1_RUN_ID
		  WHEN RUN2_SB_FL = 'T' THEN BASE2_RUN_ID
		  ELSE BASE3_RUN_ID
		END AS BASE_STL_ID
		, 3 AS STOLEN_BASE_POINTS
		, 1 AS STOLEN_BASE_FL
		FROM retrosheet.events
		WHERE event_cd='4'
		UNION
		SELECT GAME_ID
		, STR_TO_DATE(SUBSTRING(GAME_ID, 4, 8), '%Y%m%d') AS GAME_DATE
		, RUN1_SB_FL
		, RUN2_SB_FL
		, RUN3_SB_FL
		, BASE1_RUN_ID
		, BASE2_RUN_ID
		, BASE3_RUN_ID
		, PIT_HAND_CD
		, event_cd
		, CASE
		  WHEN RUN1_SB_FL = 'T' AND RUN2_SB_FL = 'T' THEN BASE2_RUN_ID
		  WHEN RUN1_SB_FL = 'T' AND RUN3_SB_FL = 'T' THEN BASE3_RUN_ID
		  WHEN RUN2_SB_FL = 'T' AND RUN3_SB_FL = 'T' THEN BASE3_RUN_ID
		  WHEN RUN1_SB_FL = 'T' THEN BASE1_RUN_ID
		  WHEN RUN2_SB_FL = 'T' THEN BASE2_RUN_ID
		  ELSE BASE3_RUN_ID
		  END AS BASE_STL_ID
		, 3 AS STOLEN_BASE_POINTS
		, 1 AS STOLEN_BASE_FL
		FROM retrosheet.events
		WHERE event_cd='4'
	) AS sb
	GROUP BY GAME_ID, GAME_DATE, BASE_STL_ID, STOLEN_BASE_FL, PIT_HAND_CD
	;

SELECT '========================================' AS '';
SELECT 'stolen_bases INSERT completed' AS '';
SELECT NOW() AS 'Completion Time';
SELECT CONCAT('Rows inserted: ', COUNT(*)) AS 'Row Count' FROM retrosheet.stolen_bases;
SELECT '========================================' AS '';

SELECT '' AS '';
SELECT '###################################' AS '';
SELECT '# ALL TABLES CREATED SUCCESSFULLY #' AS '';
SELECT '###################################' AS '';
SELECT NOW() AS 'Final Completion Time';
SELECT '' AS '';
