CREATE TABLE retrosheet.weather_data (
  Location VARCHAR(255) NOT NULL,
  TIME VARCHAR(255) NOT NULL,
  WEATHER_PARK_CD VARCHAR(255) NOT NULL,
  TEMP_PARK_CT INT(3) NOT NULL,
  WIND_SPEED_PARK_CT INT(3) NOT NULL,
  HUMIDITY_PARK_CT INT(3) NOT NULL,
  PRIMARY KEY (Location, TIME)
);