CREATE TABLE retrosheet.weather_data (
  Location VARCHAR(255) NOT NULL,
  TIME VARCHAR(255) NOT NULL,
  Weather_PARK_CD VARCHAR(255) NOT NULL,
  TEMP_PARK_CT INT(3) NOT NULL,
  Wind_SPEED_PARK_CT INT(3) NOT NULL,
  Humidity_PARK_CT INT(3) NOT NULL,
  PRIMARY KEY (Location, TIME)
);